# Fuente
font_family DejaVuSansM Nerd Font Mono
font_size 11.0

# Cursor
cursor_shape block
cursor_blink_interval 0

# Scroll
scrollback_lines 10000

# Transparencia ligera
background_opacity 0.95

# Padding
window_padding_width 8

# Tabs
tab_bar_edge top
tab_bar_style powerline

# Performance
repaint_delay 10
input_delay 3

# Titulo de la ventana
wayland_titlebar yes

# Window prompt
window_title_format {cwd} — {cmdline}

shell_integration no-title

# Navegación tipo Vim entre splits
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up

# Padding interno
window_padding_width 0

enable_audio_bell no
